### ISSUE TITLE
0除算の修正依頼

### ISSUE THREAD

**Issue by TaigaU121** [mickeyjoe666/GitExample_TechTock#6]
## 操作手順
* 0で割ったら
* 0になった

## 本来の想定
* 0で割ったら
* 計算できないでほしい

## 操作環境
* MacOS
* OSバージョン：10.15.3
* ブラウザ：GoocleChrome
* ブラウザバージョン：83.0.4103.106

**Comment by funator26** [comment]
#1と同様の内容だったのでclose
